name: Lighthouse CI
on: [push, pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Start Astro preview server
        run: npm run preview -- --port 4321 &

      - name: Wait for server
        run: |
          while ! nc -z localhost 4321; do
            sleep 3
          done

      - name: Run Lighthouse CI
        uses: foo-software/lighthouse-check-action@master
        with:
          configPath: ./lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
          urls: http://localhost:4321
          prCommentEnabled: true
          device: 'all'
          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}

