name: Playwright Tests
on: [pull_request]
jobs:
  test:
    timeout-minutes: 60
    name: Run playwright tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Start Astro preview server
        run: npm run preview -- --port 4321 &

      - name: Wait for server
        run: |
          while ! nc -z localhost 4321; do
            sleep 3
          done

      - run: PLAYWRIGHT_JSON_OUTPUT_NAME=results.json npm playwright test --reporter json

      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: results.json
